import {test} from 'node:test';import assert from 'node:assert/strict';import {initialState,newChain} from '../src/shared/model.ts';import {reduce} from '../src/shared/validation.ts';import {ConversationIndex} from '../src/conversation/index.ts';import {handoff,validateContinuation} from '../src/conversation/handoff.ts';
test('deleting a Persona changes only referencing Chains',()=>{let state=initialState();state=reduce(state,{type:'persona.save',persona:{id:'p',name:'P',instructions:'',avatars:{}},expectedVersion:0});for(const id of ['one','two']){const c=newChain(id,null);c.id=id;c.defaultPersonaId=id==='one'?'p':null;state=reduce(state,{type:'chain.save',chain:c,expectedVersion:0});}const next=reduce(state,{type:'persona.delete',id:'p',expectedVersion:1});assert.equal(next.chains[0].version,2);assert.equal(next.chains[1].version,1);});
test('handoff includes explicitly selected context and excludes unselected conversation text',()=>{const index=new ConversationIndex('a');index.hydrate(['selected','private omitted'].map((text,i)=>({conversationId:'a',id:String(i),order:i,role:'user',text,preview:text,headings:[],attachments:[],updatedAt:1})));index.annotate('0',{bookmarked:true,note:'Decision'});const c=newChain('Story',null);c.continuationMessage='Continue here';const text=handoff(index,c);assert.match(text,/selected/);assert.match(text,/Decision/);assert.match(text,/Continue here/);assert.ok(!text.includes('private omitted'));assert.throws(()=>validateContinuation({draft:'invalid'}));});
test('a continuation binds only after its actual submitted prompt appears in a new indexed session',async()=>{
 const {confirmsContinuation}=await import('../src/conversation/handoff.ts');
 const p={chainId:'c',sourceId:'old',selection:{chainId:'c',personaId:null,visualOnly:false},draft:'Reviewed handoff',createdAt:1,sentAt:100};
 const index=new ConversationIndex('new');assert.equal(confirmsContinuation(p,index,101),false);
 index.hydrate([{conversationId:'new',id:'1',role:'user',order:0,text:p.draft,preview:p.draft,headings:[],attachments:[],updatedAt:1}]);
 assert.equal(confirmsContinuation(p,index,101),true);assert.equal(confirmsContinuation(p,index,200001),false);assert.equal(confirmsContinuation({...p,sourceId:'new'},index,101),false);
 const noSend={...p};delete (noSend as any).sentAt;assert.equal(confirmsContinuation(noSend,index,101),false);
});
